#obtener orf de la siguiente sequencia AGCCATGTAGCTAACTCAGGTTACATGGGGATGACCCCGCGACTTGGATTAGAGTCTCTTTTGGAATAAGCCTGAATGATCCGAGTAGCATCTCAG

import Bio.Seq
import Bio.SeqUtils

sequence = Seq("AGCCATGTAGCTAACTCAGGTTACATGGGGATGACCCCGCGACTTGGATTAGAGTCTCTTTTGGAATAAGCCTGAATGATCCGAGTAGCATCTCAG")
codon_inicio = Seq("ATG")

pos_iniciales = nt_search(str(sequencia), inicio)

